#!/bin/bash

OK=0

if [ "$1.cpp" -nt tmp.exe ] || [ "$2" = "f" ]
then
    echo "compiling..."
    g++ -g -O2 -std=gnu++17 -static -o tmp.exe "$1.cpp"
    OK=$?
fi

(exit $OK) && echo "running..." && ./tmp.exe
