#!/bin/bash

OK=0

if [ "$1" -nt tmp ] || [ "$2" = "f" ]
then
    echo "compiling..." >&2
    g++ -Wall -g -std=c++20 -o tmp "$1"
    OK=$?
fi

(exit $OK) && echo "running..." >&2 && valgrind -q ./tmp
